# add the following to _config.yml file
title: Emmanuel Masavo DJEGOU
# theme: jekyll-theme-midnight

# Other optional configurations:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate


# theme: jekyll-theme-merlot
theme: jekyll-theme-cayman

